## Quelle: https://www.itsmarc.com/crs/mergedprojects/helptop1/helptop1/variable_data_fields/tag_list.html
## hier werden die tags aus der XML-Datei ihrer deutschen Bedeutung zugeordnet, Übersetzung: Holger mit Hilfe von DeepL
tag_meanings = {
    ('001', '', ''): 'Kontrollnummer',
    ('007', '', ''): 'Physische Beschreibung / Medientyp',
    ('008', '', ''): 'Codierte Daten (Datum, Sprache, Land, etc.)',
    ('020', ' ', ' '): 'ISBN',
    ('022', ' ', ' '): 'ISSN',
    ('040', ' ', ' '): 'Katalogisierungsquelle', ## es gibt: "rak" (regelwerk alphabetische katalogisierung), "rda" ( Resource Description and Access) und "null" (nicht ausgefüllt)
    ('041', ' ', ' '): 'Sprachcode',
    ('049', ' ', ' '): 'Lokale Bestandsnummer',
    ('084', ' ', ' '): 'Andere Notation',
    ('100', '0', ' '): 'Personenname (Vorname)',
    ('110', '0', ' '): 'Körperschaftsname',
    ('240', '0', ' '): 'Einheitstitel',
    ('245', '0', '0'): 'Haupttitel (ohne Zusatz)',
    ('245', '0', '1'): 'Haupttitel (mit Zusatz)',
    ('245', '0', '2'): 'Haupttitel (mit Angabe Paralleltitel)',
    ('245', '0', '3'): 'Haupttitel (ohne Verfasserangabe)',
    ('245', '0', '4'): 'Haupttitel und Urheberangabe',
    ('245', '0', '5'): 'Haupttitel (gemischte Verfasserangabe)',
    ('245', '0', '6'): 'Haupttitel (anonym)',
    ('245', '0', '7'): 'Haupttitel (mehrere Werke)',
    ('245', '0', '8'): 'Haupttitel (Sammelwerk)',
    ('245', '0', '9'): 'Haupttitel (Sonderfälle)',
    ('246', '1', '1'): 'Titelvarianten',
    ('246', '1', '3'): 'Titelzusatz',
    ('250', ' ', ' '): 'Ausgabebezeichnung',
    ('260', ' ', ' '): 'Verlags- und Erscheinungsangaben',
    ('300', ' ', ' '): 'Umfangsangabe',
    ('336', ' ', ' '): 'Inhaltstyp',
    ('338', ' ', ' '): 'Datenträgertyp',
    ('490', '0', '#'): 'Gesamttitel nicht verwiesen',
    ('500', ' ', ' '): 'Allgemeine Anmerkung',
    ('520', ' ', ' '): 'Zusammenfassung oder Abstract',
    ('520', '1', ' '): 'unformatierte Zusammenfassung (Rezensionen, Anmerkungen etc.)',
    ('653', ' ', ' '): 'Schlagwörter oder Indexierungsterm',
    ('653', ' ', '1'): 'Personenname als Schlagwort',
    ('653', ' ', '2'): 'Körperschaftsname als Schlagwort',
    ('653', ' ', '4'): 'Zeitschlagwort',
    ('653', ' ', '5'): 'Geografische Angabe als Schlagwort',
    ('653', ' ', '6'): 'Genre oder Formbegriff als Schlagwort',
    ('700', '0', ' '): 'Weiterer Personennamen (Vorname)',
    ('773', '0', '1'): 'Angaben zur übergeordneten Einheit',
    ('969', '#', '#'): 'Lokale administrative Daten (Systeminformationen)',
}
## Quelle Anpassung-Übersetzung: https://www.alma-dach.org/alma-marc/bibliographic/ durch Sophie
