## Quelle: https://www.itsmarc.com/crs/mergedprojects/helptop1/helptop1/variable_data_fields/tag_list.html
## hier werden die tags aus der XML-Datei ihrer deutschen Bedeutung zugeordnet, Übersetzung: Holger mit Hilfe von DeepL
tag_meanings = {
    ('001', '', ''): 'Kontrollnummer',
    ('007', '', ''): 'Physische Beschreibung / Medientyp',
    ('008', '', ''): 'Festcodierte Daten (Datum, Sprache, Land, etc.)',
    ('020', ' ', ' '): 'ISBN',
    ('022', ' ', ' '): 'ISSN',
    ('040', ' ', ' '): 'Katalogisierungsstandard', ## es gibt: "rak" (regelwerk alphabetische katalogisierung), "rda" ( Resource Description and Access) und "null" (nicht ausgefüllt)
    ('041', ' ', ' '): 'Sprachcode',
    ('049', ' ', ' '): 'Lokale Besitzinformation',
    ('084', ' ', ' '): 'Klassifikationsnummer',
    ('100', '0', ' '): 'Personenname (Vorname zuerst)',
    ('110', '0', ' '): 'Körperschaftsname',
    ('240', '0', ' '): 'Einheitstitel',
    ('245', '0', '0'): 'Haupttitel (ohne Zusatz)',
    ('245', '0', '1'): 'Haupttitel (mit Zusatz)',
    ('245', '0', '2'): 'Haupttitel (mit Angabe paralleler Titel)',
    ('245', '0', '3'): 'Haupttitel (ohne Verfasserangabe)',
    ('245', '0', '4'): 'Haupttitel und Urheberangabe',
    ('245', '0', '5'): 'Haupttitel (gemischte Verfasserangabe)',
    ('245', '0', '6'): 'Haupttitel (anonym)',
    ('245', '0', '7'): 'Haupttitel (mehrere Werke)',
    ('245', '0', '8'): 'Haupttitel (Sammelwerk)',
    ('245', '0', '9'): 'Haupttitel (Sonderfälle)',
    ('246', '1', '1'): 'Variantenform des Titels',
    ('246', '1', '3'): 'Titelzusatz',
    ('250', ' ', ' '): 'Ausgabebezeichnung',
    ('260', ' ', ' '): 'Verlags- und Erscheinungsangaben',
    ('300', ' ', ' '): 'Physische Beschreibung (Umfang)',
    ('336', ' ', ' '): 'Inhaltstyp',
    ('338', ' ', ' '): 'Datenträgertyp',
    ('490', '0', '#'): 'Reihentitel (ungeprüfte Reihe)',
    ('500', ' ', ' '): 'Allgemeine Anmerkung',
    ('520', ' ', ' '): 'Zusammenfassung oder Abstract',
    ('520', '1', ' '): 'Rezension oder Bewertung',
    ('653', ' ', ' '): 'Freie Schlagwörter',
    ('653', ' ', '1'): 'Person als Schlagwort',
    ('653', ' ', '2'): 'Organisation als Schlagwort',
    ('653', ' ', '4'): 'Chronologische Angabe als Schlagwort',
    ('653', ' ', '5'): 'Geografische Angabe als Schlagwort',
    ('653', ' ', '6'): 'Gattung/Formschlagwort',
    ('700', '0', ' '): 'Weiterer Personenname (Vorname zuerst)',
    ('773', '0', '1'): 'Angaben zur übergeordneten Einheit',
    ('969', '#', '#'): 'Lokale administrative Daten (Systeminformationen)',
}
